export const VERTEX_CREATED_WHILE_DRAWING = 'VERTEX_CREATED_WHILE_DRAWING';
export const POLYGON_CREATED = 'POLYGON_CREATED';
export const VERTEX_MODIFIED_IN_POLYGON = 'VERTEX_MODIFIED_IN_POLYGON';
export const VERTEX_ADDED_IN_POLYGON = 'VERTEX_ADDED_IN_POLYGON';
export const VERTEX_DELETED_IN_POLYGON = 'POLYGON_CREATED';
export const POLYGON_DELETED = 'POLYGON_DELETED';
export const SHOW_MESSAGE = 'ShowMessage';
export const SET_STATUS_MESSAGE = 'SetStatusMessage';
